### ISSUE TITLE
Homework: install some tools to get a Linux environment up and running

### ISSUE THREAD

**Issue by RobbKistler** [ckons/curry-bubble#2]
@ckons

Install VirtualBox.  This is free software that will let you run a virtual machine on your mac.  For instance, you can run Windows!  But we're going to use it for Linux.  

https://www.virtualbox.org

In the not-so-distant past, you'd now have to go install Linux into the VM and generally have a headache.  But this is a bold new world, so also install this:

https://www.vagrantup.com

Once you're done, I'm going to check a very small file into this repo that will bring up a small Linux installation almost immediately, and it will stay in sync exactly with what I have.

**Comment by ckons** [comment]
Acquired and installed
